language: go

go:
  - "1.9.x"
  - "1.10.x"

install:
  - go get -u github.com/golang/dep/...
  - dep ensure

# Don't email me the results of the test runs.
notifications:
  email: false

script:
- go test -v -race $(go list ./... | grep -v /vendor/)  # Run all the tests with the race detector enabled
- go build ./cmd/...
