name: CI
on: [push, pull_request]
jobs:
  build-all:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.13
    - run: go build ./cmd/...
