name: CI
on: [push, pull_request]
jobs:
  build-all:
    name: go-${{ matrix.go-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        go-version: [1.12, 1.13, 1.14]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.13
    - run: go build ./cmd/...
