name: CI
on: [push, pull_request]
jobs:
  build-all:
    name: go-${{ matrix.go-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        go-version: [1.15, 1.16, 1.17, 1.18]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - run: go build ./cmd/...
