name: CI
on: [push, pull_request]
jobs:
  build-all:
    name: go-${{ matrix.go-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        go-version: ['1.18', '1.19', '1.20']
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - run: go build ./cmd/...
